spring.application.name=EmployeeLT
spring.datasource.url=jdbc:snowflake://vt77123.ap-southeast-1.snowflakecomputing.com
spring.datasource.username=SIVASANKAR16
spring.datasource.password=Ramamohan40126
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver

# ✅ Important: move params here
spring.datasource.hikari.data-source-properties.database=EMPLOYEE_DB
spring.datasource.hikari.data-source-properties.schema=PUBLIC
spring.datasource.hikari.data-source-properties.warehouse=COMPUTE_WH

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration