spring.application.name=EmployeeLT
spring.datasource.url=jdbc:snowflake://NERDZIP-WQ74543.snowflakecomputing.com

spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver

# ✅ Important: move params here
spring.datasource.hikari.data-source-properties.database=EMPLOYEE_DB
spring.datasource.hikari.data-source-properties.schema=PUBLIC
spring.datasource.hikari.data-source-properties.warehouse=COMPUTE_WH

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
